config/routes.rb
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin? } do
    mount Motor::Admin => '/motor_admin'
  end
  devise_for :users
  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  root to: "pages#home"
  get 'terms-and-conditions', to: 'pages#terms'
  get 'privacy-policy', to: 'pages#privacy'
  get 'cookies', to: 'pages#cookies'


  resources :journals, except: :destroy do
    resources :journalpages, except: :destroy
  end
  resources :journalpages, only: :destroy
  resources :journals, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_many :journalpages, dependent: :destroy
end

app/models/journalpage.rb
class Journalpage < ApplicationRecord
  belongs_to :journal

  validates :answer, format: { with: /\A[a-zA-Z0-9\s]*\z/, message: "only allows letters, numbers, and spaces" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  pay_customer stripe_attibutes: :stripe_attibutes
  has_many :journals

  def stripe_attributes(pay_customer)
    {
      address: {
        city: pay_customer.address_city,
        country: pay_customer.address_country,
      },
      metadata: {
        pay_customer_id: pay_customer.id,
        user_id: id, # or pay_customer.owner_id
      }
    }
  end

  def premium?
    self.charges.any?
  end

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_locale

  def set_locale
    I18n.locale = current_user.try(:locale) || I18n.default_locale
  end

  # This method overrides Rails.application.default_url_options[:host] to add an absolute URL to meta tags, good for SEO
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def after_sign_in_path_for(resource)
    journals_path
  end

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  def show
    current_user.set_payment_processor :stripe
    current_user.payment_processor.customer

    @checkout_session = current_user.payment_processor.checkout(
      mode: 'payment',
      line_items: ENV[:STRIPE_PRICE_ID], # Set in .env file
      success_url: checkout_success_url
    )
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @line_items = Stripe::Checkout::Session.list_line_items(@session.id)
  end
end

app/controllers/journalpages_controller.rb
class JournalpagesController < ApplicationController

  def index
    @journal = Journal.find(params[:journal_id]) # Find the parent journal
    @journalpages = @journal.journalpages       # Get only the journal pages for the parent journal
  end

  def show
    @journal = Journal.find(params[:journal_id]) # Find the parent journal
    @journalpage = Journalpage.find(params[:id]) # Find the parent journal
  end

  def new
    @journal = Journal.find(params[:journal_id])
    @journalpage = Journalpage.new
    topic = @journal.topic
    client = OpenAI::Client.new

    # Call OpenAI API
    begin
      chatgpt_response = client.chat(
        parameters: {
          model: "llama3.2", # Ensure you're using a valid model
          messages: [
            { role: "user", content: "You are a young therapist. Generate a concise, reflective journal question for the topic #{topic}'. Provide one question directly. Avoid introductory text or fluff and dont say core question or sub." }
          ],
          max_tokens: 100
        }
      )
      @content = chatgpt_response["choices"][0]["message"]["content"]
    rescue StandardError => e
      @content = "Sorry, we couldn't generate a question at this time. Please try again."
      Rails.logger.error("OpenAI API Error: #{e.message}")
    end
  end





  def create
    @journalpage = Journalpage.new(journalpage_params)
    @journal = Journal.find(params[:journal_id])
    @journalpage.journal_id = @journal.id
    if @journalpage.save
      redirect_to journal_journalpages_path(@journal)
    else
      render :new
    end
  end

  def destroy
    @journalpage = Journalpage.find(params[:id])
    @journalpage.destroy
    redirect_to journal_journalpages_path(@journalpage.journal), status: :see_other
  end

  private

  def journalpage_params
    params.require(:journalpage).permit(:prompt, :answer)
  end



end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  def index
    @journals = Journal.all
  end

  def show
    @journal = Journal.find(params[:id])
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.user = current_user
    if @journal.save!
      redirect_to journals_path, notice: "Journal successfully created!"
    else
      render :new
    end
  end

  def destroy
    @journal = Journal.find(params[:id])
    @journal.destroy
    redirect_to journals_path, status: :see_other
  end

  private

  def journal_params
    params.require(:journal).permit(:name, :topic)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def terms
  end

  def privacy
  end

  def cookies
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/journalpages_helper.rb
module JournalpagesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/checkouts/show.html.erb
<div class="py-24 sm:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8 ">
    <div class="mx-auto max-w-2xl sm:text-center">
      <h2 class="text-3xl font-bold tracking-tight sm:text-4xl">Simple no-tricks pricing</h2>
      <p class="mt-6 text-lg leading-8">Distinctio et nulla eum soluta et neque labore quibusdam. Saepe et quasi iusto modi velit ut non voluptas in. Explicabo id ut laborum.</p>
    </div>
    <div class="card lg:card-side bg-base-100 shadow-xl mt-6">
      <figure>
        <img
          src="https://img.daisyui.com/images/stock/photo-1494232410401-ad00d5433cfa.webp"
          alt="Album" />
      </figure>
      <div class="card-body justify-between">
        <div class="flex justify-between">
          <div>
            <h2 class="card-title">Pro Plan</h2>
            <p class="text-base font-semibold">Pay once, own it forever</p>
          </div>
          <p class="flex items-baseline gap-x-2 justify-end mb-6">
            <span class="text-5xl font-bold tracking-tight">$40</span>
            <span class="text-sm font-semibold leading-6 tracking-wide">USD</span>
          </p>
        </div>
        <ul>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Private forum access
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Member resources
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Entry to annual conference
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Official member t-shirt
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Invoices and receipts available for easy company reimbursement
          </li>
        </ul>
        <div class="card-actions justify-end">
          <%= render partial: 'pay/stripe/checkout_button', locals: { title: "Checkout", session: @checkout_session }, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/checkouts/success.html.erb
<div class="py-24 sm:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8 ">
    <div class="card lg:card-side bg-base-100 shadow-xl mt-6">
      <figure>
        <img
          src="https://img.daisyui.com/images/stock/photo-1494232410401-ad00d5433cfa.webp"
          alt="Album" />
      </figure>
      <div class="card-body justify-between">
        <div class="flex justify-between">
          <div>
            <h2 class="card-title">Thank you! 🚀</h2>
            <p class="text-base font-semibold">You are now a Pro plan user, with unlimited access to:</p>
          </div>
          <p class="flex items-baseline gap-x-2 justify-end mb-6">
            <span class="text-5xl font-bold tracking-tight"><%= @session.amount_total.to_f / 100 %></span>
            <span class="text-sm font-semibold leading-6 tracking-wide">USD</span>
          </p>
        </div>
        <ul>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Private forum access
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Member resources
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Entry to annual conference
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Official member t-shirt
          </li>
          <li class="flex items-center gap-2">
            <%= lucide_icon "check" %>
            Invoices and receipts available for easy company reimbursement
          </li>
        </ul>
        <div class="card-actions justify-end">
          <%= link_to "Start now", root_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/journalpages/index.html.erb
<div class="overflow-x-auto">
  <table class="table">
    <!-- head -->
    <thead>
      <tr>
        <th>#</th>
        <th>Date</th>
        <th>Title</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @journalpages.each_with_index do |page, index| %>
        <tr class="hover">
            <th><%= index + 1 %></th>
            <td><%= page.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            <td><%= truncate(page.prompt, length: 100, omission: "...") %></td>
            <td>
              <%= link_to "Show", journal_journalpage_path(@journal, page), class: "btn btn-sm btn-secondary" %>
              <%= link_to "Delete", journalpage_path(page),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "btn btn-sm btn-primary" %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/journalpages/new.html.erb
<%= form_with(model: @journalpage, url: [@journal, @journalpage]) do |f| %>
  <div class="flex flex-col items-center justify-center min-h-2/4 mt-0 bg-opacity-75 bg-white rounded-lg shadow-xl p-6 max-w-lg mx-auto">
    <div class="flex items-center space-x-2">
  <%= f.label :answer, @content, class: "text-lg font-medium" %>
  <a href="#" onclick="location.reload()" class="text-primary-content"><%= lucide_icon("rotate-ccw") %></a>
</div>
<%= f.text_area :answer, class: "textarea textarea-bordered w-full h-96 mt-2", rows: 10 %>
    <div class="form-actions mt-4">
      <%= f.submit "Save Journal Page", class: "btn btn-primary" %>
      <%= f.hidden_field :prompt, value: @content %>
    </div>
  </div>
<% end %>

app/views/journalpages/show.html.erb
<div class="flex flex-col items-center min-h-screen mt-0">
  <div class="mb-4 w-full max-w-3xl">
    <h2 class="text-lg font-medium mb-4">
      <%= @journalpage.prompt %>
    </h2>
    <p class="textarea textarea-bordered w-full h-96 p-4 bg-base-100 text-secondary-content rounded-lg leading-relaxed">
      <%= @journalpage.answer %>
    </p>
  </div>
  <div class="form-actions mt-4">
    <%= link_to "Back to Pages", journal_journalpages_path(@journal), class: "btn btn-primary" %>
  </div>
</div>

app/views/journals/index.html.erb
<div class="flex flex-col items-center justify-center bg-opacity-75 bg-white rounded-lg shadow-xl p-6 max-w-md mx-auto">
  <h1 class="text-2xl font-bold mb-4">My journals:</h1>
  <ul class="space-y-2">
    <% @journals.each do |journal| %>
      <li class="flex items-center space-x-2 relative">
        <%= link_to journal.name, new_journal_journalpage_path(journal), class: "btn btn-wide" %>
        <%= link_to lucide_icon("circle-x"), journal_path(journal),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "absolute right-0 top-0 transform translate-x-[-12px] translate-y-3 text-[#6b6667]" %>
      </li>
    <% end %>
    <li><%= link_to "Create New Journal", new_journal_path, class: "btn btn-wide btn-primary" %></li>
  </ul>
</div>

app/views/journals/new.html.erb
<%= form_for @journal, html: { class: "space-y-4 w-full max-w-md mx-auto bg-white p-6 rounded-lg shadow-md" } do |f| %>
  <div class="form-group">
    <label for="journal_name" class="block text-sm font-medium text-gray-700 mb-2">Journal Name</label>
    <%= f.text_field :name, id: "journal_name", placeholder: "Enter the journal name", class: "input input-bordered w-full" %>
  </div>

  <div class="form-group">
    <label for="journal_topic" class="block text-sm font-medium text-gray-700 mb-2">Journal Topic</label>
    <%= f.text_field :topic, id: "journal_topic", placeholder: "Enter the journal topic", class: "input input-bordered w-full" %>
  </div>

  <div class="form-actions">
    <%= f.submit "Create Journal", class: "btn btn-primary w-full" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="retro">
  <head>
    <title>myJournal.ai</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <%# Facebook Open Graph data  %>
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%# Twitter Card data %>
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%# Change your favicon in assets/images/favicon.png  %>
    <%= favicon_link_tag 'favicon.png' %>

    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <div class="grid min-h-screen grid-rows-[auto_1fr_auto] bg-[url('<%= asset_path("wallpaper.jpeg") %>')]">
      <%= render "shared/navbar" %>
      <main class="container mx-auto mt-8 min-h-screen">
        <%= render "shared/alerts" %>
        <%= yield %>
      </main>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/cookies.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cookie Policy</title>
</head>
<body class="font-sans">
  <div class="max-w-4xl mx-auto py-12 px-6 sm:px-8 lg:px-12 shadow-lg rounded-lg my-6">
    <h1 class="text-4xl font-bold mb-8 text-center">Cookie Policy</h1>

    <p class="text-sm mb-12 text-center">Last Updated: [Date]</p>

    <div class="space-y-8">
      <section>
        <h2 class="text-2xl font-semibold mb-4">1. Introduction</h2>
        <p class="leading-relaxed">
          This Cookie Policy explains how [Company Name] ("we", "us", or "our") uses cookies and similar technologies to recognize you when you visit our website at [Website URL] (the "Website").
          It explains what these technologies are and why we use them, as well as your rights to control our use of them.
        </p>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4">2. What Are Cookies?</h2>
        <p class="leading-relaxed">
          Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners to make their websites work, or to work more efficiently, as well as to provide reporting information.
          Cookies set by the website owner (in this case, [Company Name]) are called "first-party cookies." Cookies set by parties other than the website owner are called "third-party cookies."
          Third-party cookies enable third-party features or functionality to be provided on or through the website (e.g., advertising, interactive content, and analytics). The parties that set these third-party cookies can recognize your computer both when it visits the website in question and also when it visits certain other websites.
        </p>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4">3. Why We Use Cookies</h2>
        <p class="leading-relaxed">
          We use first-party and third-party cookies for several reasons. Some cookies are required for technical reasons for our Website to operate, and we refer to these as "essential" or "strictly necessary" cookies.
          Other cookies enable us to track and target the interests of our users to enhance the experience on our Website. Third parties serve cookies through our Website for advertising, analytics, and other purposes.
        </p>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4">4. Types of Cookies We Use</h2>
        <p class="leading-relaxed">
          The specific types of first- and third-party cookies served through our Website and the purposes they perform are described below:
        </p>
        <ul class="list-disc list-inside leading-relaxed ml-4">
          <li><strong>Essential Cookies:</strong> These cookies are strictly necessary to provide you with services available through our Website and to use some of its features.</li>
          <li><strong>Performance and Functionality Cookies:</strong> These cookies are used to enhance the performance and functionality of our Website but are non-essential to their use.</li>
          <li><strong>Analytics and Customization Cookies:</strong> These cookies collect information that is used either in aggregate form to help us understand how our Website is being used or how effective our marketing campaigns are, or to help us customize our Website for you.</li>
          <li><strong>Advertising Cookies:</strong> These cookies are used to make advertising messages more relevant to you. They perform functions like preventing the same ad from continuously reappearing, ensuring that ads are properly displayed, and in some cases, selecting advertisements that are based on your interests.</li>
        </ul>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4">5. Your Choices Regarding Cookies</h2>
        <p class="leading-relaxed">
          You have the right to decide whether to accept or reject cookies. You can exercise your cookie preferences by clicking on the appropriate opt-out links provided in the cookie notice on our Website.
          You can set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our Website, though your access to some functionality and areas of our Website may be restricted. As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information.
        </p>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4">6. More Information</h2>
        <p class="leading-relaxed">
          If you have any questions about our use of cookies or other technologies, please email us at [Email Address].
        </p>
      </section>
    </div>
  </div>
</body>

app/views/pages/home.html.erb
<%= render "components/hero" %>
<%= render "components/problem_statement" %>

app/views/pages/privacy.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy</title>
</head>
<body class="font-sans">
  <div class="max-w-4xl mx-auto py-12 px-6 sm:px-8 lg:px-12 shadow-lg rounded-lg my-6">
    <h1 class="text-4xl font-bold mb-8 text-center ">Privacy Policy</h1>

    <p class="text-sm  mb-12 text-center">Last Updated: [Date]</p>

    <div class="space-y-8">
      <section>
        <h2 class="text-2xl font-semibold mb-4 ">1. Introduction</h2>
        <p class=" leading-relaxed">
          [Company Name] ("we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and disclose your information when you use [Product Name] (the "Service").
          By using the Service, you agree to the collection and use of information in accordance with this policy.
        </p>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4 ">2. Information We Collect</h2>
        <p class=" leading-relaxed">
          We collect various types of information in connection with the Service, including:
        </p>
        <ul class="list-disc list-inside  leading-relaxed ml-4">
          <li><strong>Personal Information:</strong> Such as your name, email address, billing address, and payment details when you register or make a purchase.</li>
          <li><strong>Usage Data:</strong> Information on how you access and use the Service, including your IP address, browser type, and device information.</li>
          <li><strong>Cookies and Tracking Data:</strong> We use cookies and similar tracking technologies to track activity on our Service and hold certain information.</li>
        </ul>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4 ">3. How We Use Your Information</h2>
        <p class=" leading-relaxed">
          [Company Name] uses the collected data for various purposes, including:
        </p>
        <ul class="list-disc list-inside  leading-relaxed ml-4">
          <li>To provide and maintain the Service</li>
          <li>To process transactions and manage your account</li>
          <li>To improve and personalize your experience with the Service</li>
          <li>To communicate with you about updates, promotions, and other news related to the Service</li>
          <li>To detect, prevent, and address technical issues or security threats</li>
        </ul>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4 ">4. Sharing of Information</h2>
        <p class=" leading-relaxed">
          We do not sell, trade, or otherwise transfer your personal information to third parties except in the following circumstances:
        </p>
        <ul class="list-disc list-inside  leading-relaxed ml-4">
          <li>With service providers who assist us in operating our Service or conducting our business, so long as those parties agree to keep this information confidential</li>
          <li>When required by law or in response to valid requests by public authorities</li>
          <li>To protect and defend the rights or property of [Company Name]</li>
          <li>In connection with a merger, acquisition, or sale of all or a portion of our assets</li>
        </ul>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4 ">5. Security of Your Information</h2>
        <p class=" leading-relaxed">
          The security of your personal information is important to us. We implement appropriate technical and organizational measures to protect your information against unauthorized access, alteration, disclosure, or destruction.
          However, please be aware that no method of transmission over the internet or method of electronic storage is 100% secure, and we cannot guarantee its absolute security.
        </p>
      </section>

      <section>
        <h2 class="text-2xl font-semibold mb-4 ">6. Data Retention</h2>
        <p class=" leading-relaxed">
          We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.
        </p>
      </section>
    </div>
  </div>
</body>

app/views/shared/_alerts.html.erb
<% if notice || alert %>
  <div
    id="flash-alert"
    role="alert"
    class="alert fixed bottom-0 left-0 w-6/12 m-4 bg-base-300 text-neutral shadow-lg rounded-box z-50">
    <%= lucide_icon("message-circle-warning") %>
    <span><%= notice %> <%= alert %></span>
      <form method="dialog">
        <%# Add a button to close the dialog %>
      </form>
  </div>

  <script>
    // Automatically remove the alert after 5 seconds
    setTimeout(() => {
      const alertElement = document.getElementById('flash-alert');
      if (alertElement) {
        alertElement.remove();
      }
    }, 5000); // 5000ms = 5 seconds
  </script>
<% end %>

app/views/shared/_footer.html.erb
<%#
<footer class="footer bg-base-200 text-base-content p-10">
  <aside>
    <%= image_tag 'logo.png', alt: 'Logo', class: 'fill-current h-8' %>
   <%#  <p>
      ACME Industries Ltd.
      <br />
      Providing reliable tech since 1992
    </p>
    <%= link_to "🚀 Powered by LightningRails", "https://lightningrails.com", class: 'btn btn-neutral' %>
  <%# </aside>
 <%#  <nav>
    <h6 class="footer-title">Services</h6>
    <%= link_to 'Branding', '#', class: 'link link-hover' %>
  <%#   <%= link_to 'Design', '#', class: 'link link-hover' %>
 <%#    <%= link_to 'Marketing', '#', class: 'link link-hover' %>
 <%#    <%= link_to 'Advertisement', '#', class: 'link link-hover' %>
<%#   </nav>
  <nav>
    <h6 class="footer-title">Company</h6>
    <%= link_to 'About us', '#', class: 'link link-hover' %>
<%#     <%= link_to 'Contact', '#', class: 'link link-hover' %>
  <%#   <%= link_to 'Jobs', '#', class: 'link link-hover' %>
 <%#    <%= link_to 'Press kit', '#', class: 'link link-hover' %>
 <%#  </nav>
  <nav>
    <h6 class="footer-title">Legal</h6>
    <%= link_to 'Terms of use',  terms_and_conditions_path, class: 'link link-hover' %>
 <%#    <%= link_to 'Privacy policy', privacy_policy_path, class: 'link link-hover' %>
<%# <%#     <%= link_to 'Cookie policy', cookies_path, class: 'link link-hover' %>
 <%#  </nav>
</footer>
%>

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100 bg-opacity-75 bg-white p-2 rounded-lg">
  <div class="navbar-start">
    <div class="lg:hidden dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-5 w-5"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M4 6h16M4 12h8m-8 6h16" />
        </svg>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
        <% if user_signed_in? %>
          <li><%= button_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
    <%= link_to journals_path, class: "btn btn-ghost text-xl" do %>
      <%= image_tag "logo.png", alt: "Logo", class: "h-8" %>
      Journal.ai
    <% end %>
  </div>
  <div class="navbar-center hidden lg:flex">

  </div>
  <div class="navbar-end">
  <ul class="menu menu-horizontal px-1">
      <% if user_signed_in? %>
        <li><%= button_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul>
    <% if user_signed_in? %>
    <% else %>
      <%= link_to "Get started", new_user_registration_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>